  server:
    port: 9997
  Spring:
    application:
      name: oauth2-service
    main:
      allow-bean-definition-overriding: true

    cloud:
      nacos:
        discovery:
          server-addr: 192.168.32.1:9001
#          server-addr: 198.10.1.58:9001
        config:
          server-addr: 192.168.32.1:9001
#          server-addr: 198.10.1.58:9001
          file-extension: yaml

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oauth?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
      password: 1111
      username: root
